### PR TITLE
My branch

### PR DESCRIPTION
**Pull request by BElesger**
Test doc/img  deleted

### CODE REVIEW

**Comment by johansolve** [comment]
Rejected

**Comment by stevepiercy** [comment]
Users @BElesger and @elesger attempted to delete files from the repo https://github.com/knop-project/knop/. Obvious malicious accounts based on no positive activity. Blocked and reported.

**Comment by BElesger** [comment]
Hi i dont want to delete any thing.I want to practise.Im new here. Sorry about that

**Comment by johansolve** [comment]
Ok, practise more, but maybe not here

**Comment by BElesger** [comment]
Ok i will try , thank you for understanding.

**Pull request closed without merging**
